In [1]:
# Import libraries
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
import pandas as pd 

In [19]:
df = pd.read_excel(r'C:\Users\hp\OneDrive\Desktop\CDAC-DBDA\module 7\Machine Learning\lab exam\data_final.xlsx')

In [20]:
df.head()

observation  feature   price
0         0.44     0.68  511.14
1         0.99     0.23  717.10
2         0.84     0.29  607.91
3         0.28     0.45  270.40
4         0.07     0.83  289.88

In [21]:
df.shape

(100, 3)

In [22]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [23]:
x

array([[0.44, 0.68],
       [0.99, 0.23],
       [0.84, 0.29],
       [0.28, 0.45],
       [0.07, 0.83],
       [0.66, 0.8 ],
       [0.73, 0.92],
       [0.57, 0.43],
       [0.43, 0.89],
       [0.27, 0.95],
       [0.43, 0.06],
       [0.87, 0.91],
       [0.78, 0.69],
       [0.9 , 0.94],
       [0.41, 0.06],
       [0.52, 0.17],
       [0.47, 0.66],
       [0.65, 0.43],
       [0.85, 0.64],
       [0.93, 0.44],
       [0.41, 0.93],
       [0.36, 0.43],
       [0.78, 0.85],
       [0.69, 0.07],
       [0.04, 0.52],
       [0.17, 0.15],
       [0.68, 0.13],
       [0.84, 0.6 ],
       [0.38, 0.4 ],
       [0.12, 0.65],
       [0.62, 0.17],
       [0.79, 0.97],
       [0.82, 0.04],
       [0.91, 0.53],
       [0.35, 0.85],
       [0.57, 0.69],
       [0.52, 0.22],
       [0.31, 0.15],
       [0.6 , 0.02],
       [0.99, 0.91],
       [0.48, 0.76],
       [0.3 , 0.19],
       [0.58, 0.62],
       [0.65, 0.17],
       [0.6 , 0.69],
       [0.95, 0.76],
       [0.47, 0.23],
       [0.15,

In [24]:
y

array([ 511.14,  717.1 ,  607.91,  270.4 ,  289.88,  830.85, 1038.09,
        455.19,  640.17,  511.06,  177.03, 1242.52,  891.37, 1339.72,
        169.88,  276.05,  517.43,  522.25,  932.21,  851.25,  640.11,
        308.68, 1046.05,  332.4 ,  171.85,  109.55,  361.97,  872.21,
        303.7 ,  256.38,  341.2 , 1194.63,  408.6 ,  895.54,  518.25,
        638.75,  301.9 ,  163.38,  240.77, 1449.05,  609.  ,  174.59,
        593.45,  355.96,  671.46, 1193.7 ,  278.88,  411.4 ,   42.08,
        166.19,   58.62,  642.45,  368.14,  702.78,  615.74,  143.79,
        109.  ,  328.28,  205.16, 1360.49,  905.83,  487.33,  202.76,
        202.01,  148.87,  745.3 ,  503.04, 1563.82,  165.21,  438.4 ,
         98.47,  819.63,  174.44,  483.13,  534.24,  572.31,  957.61,
        518.29, 1143.49, 1211.31,  784.74,  283.7 ,  684.38,  719.46,
        292.23,  775.68,  130.77,  801.6 ,  323.55,  726.9 ,  661.12,
        771.11, 1016.14,  237.69,  325.89,  636.22,  272.12,  696.65,
        434.53,  593

In [25]:
# split dataset training between training and test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=1)

In [28]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [29]:
x_train

array([[ 1.04758918e+00, -6.94488088e-01],
       [ 1.32046549e+00, -1.55279779e+00],
       [ 1.14991780e+00, -4.63404708e-01],
       [-1.13542124e+00, -3.31357062e-01],
       [ 1.35457502e+00, -1.99309416e-01],
       [ 1.26631659e-01,  6.25988372e-01],
       [-6.57887712e-01, -1.23794668e-03],
       [ 1.04758918e+00,  3.28881168e-01],
       [-2.14463720e-01, -8.92559557e-01],
       [ 2.28960273e-01, -1.58580970e+00],
       [ 1.55923225e+00,  1.61634572e+00],
       [ 8.08822417e-01, -4.63404708e-01],
       [ 3.31288887e-01,  2.62857345e-01],
       [ 1.55923225e+00, -1.22267867e+00],
       [ 6.72384266e-01, -1.61882161e+00],
       [-1.80354182e-01,  8.57071753e-01],
       [-1.78350246e+00, -1.55279779e+00],
       [ 1.28635595e+00,  1.48429807e+00],
       [ 5.35946114e-01, -1.42075014e+00],
       [-6.23778174e-01,  1.15417896e+00],
       [-7.94325864e-01, -1.38773823e+00],
       [ 1.45690364e+00, -8.26535734e-01],
       [-2.14463720e-01,  4.93940726e-01],
       [-4.

In [33]:
# applying polynomial feature for generate new matrix
from sklearn.preprocessing import PolynomialFeatures
pl = PolynomialFeatures(degree=3,interaction_only=False,include_bias=True)

In [44]:
# applying linear regression model
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm1 = lm.fit(pl.fit_transform(np.array(x)), y)
lm1

LinearRegression()